import { type Permission } from '@/components/__generated__/LoginAuthMutation.graphql'

export enum localState {
    USER = 'user',
    ACCESS_TOKEN = 'accessToken',
    REFRESH_TOKEN = 'refreshToken',
    TITLE_CARDS = 'titleCards',
}

export const errorMessages = {
    INVALID_CREDENTIALS: {
        serverError: 'auth_login_with_email_and_password_unspecified_auth',
        niceName: 'Das Passwort oder der Benutzername ist ungültig.'
    }
}

export const allPermissions: Permission[] = [
"AccountPermission_AVGSPotentialAnalysis_IsAVGSAccount",
"AccountPermission_AZAVAdmin_IsAZAVAccount",
"AccountPermission_AccountMemberManagement_CanInviteOrAddUsersToUserInAccountGroups",
"AccountPermission_Auth_IsBusinessAccount",
"AccountPermission_Auth_usePlacement",
"AccountPermission_CoachingCoachProfileAdmin_IsCoachAccount",
"AccountPermission_System_Root",
"UserInAccountPermission_AVGSPotentialAnalysis_IsAVGSAdmin",
"UserInAccountPermission_AVGSPotentialAnalysis_IsAVGSCoach",
"UserInAccountPermission_AVGSPotentialAnalysis_ModifyAdmin",
"UserInAccountPermission_AVGSPotentialAnalysis_ReadAdmin",
"UserInAccountPermission_AZAVAdmin_Modify",
"UserInAccountPermission_AZAVAdmin_Read",
"UserInAccountPermission_AsyncElementTaskAdmin_Modify",
"UserInAccountPermission_AsyncElementTaskAdmin_Read",
"UserInAccountPermission_AuthAdmin_MinimalRead",
"UserInAccountPermission_AuthAdmin_Modify",
"UserInAccountPermission_AuthAdmin_Read",
"UserInAccountPermission_Auth_Modify",
"UserInAccountPermission_Auth_Read",
"UserInAccountPermission_CachingAdmin_Modify",
"UserInAccountPermission_CoachBillingAdmin_Read",
"UserInAccountPermission_CoachFeedback_Read",
"UserInAccountPermission_CoachingAvailabilityAdmin_ModifyAvailability",
"UserInAccountPermission_CoachingAvailabilityAdmin_ReadAvailability",
"UserInAccountPermission_CoachingCoachProfileAdmin_ModifyCoachProfiles",
"UserInAccountPermission_CoachingCoachProfileAdmin_ReadCoachProfiles",
"UserInAccountPermission_CoachingOfferAdmin_Modify",
"UserInAccountPermission_CoachingOfferAdmin_Read",
"UserInAccountPermission_ContractPartnerAdmin_Modify",
"UserInAccountPermission_ContractPartnerAdmin_Read",
"UserInAccountPermission_CustomerFeedback_Modify",
"UserInAccountPermission_CustomerFeedback_Read",
"UserInAccountPermission_DiscountAdmin_Modify",
"UserInAccountPermission_DiscountAdmin_Read",
"UserInAccountPermission_Email_Templates",
"UserInAccountPermission_ExternalLicenseAdmin_Modify",
"UserInAccountPermission_ExternalLicenseAdmin_Read",
"UserInAccountPermission_FeatureToggleAdmin_Modify",
"UserInAccountPermission_FeatureToggleAdmin_Read",
"UserInAccountPermission_Files_Delete",
"UserInAccountPermission_GenerateCartLinkAdmin_Modify",
"UserInAccountPermission_Instructors_CreateInstructors",
"UserInAccountPermission_Instructors_DeleteInstructors",
"UserInAccountPermission_Instructors_ReadInstructors",
"UserInAccountPermission_Instructors_UpdateInstructors",
"UserInAccountPermission_LearnStates_ReadLearnStates",
"UserInAccountPermission_LearnableAdmin_Modify",
"UserInAccountPermission_LearnableAdmin_Read",
"UserInAccountPermission_LicenseAdmin_Modify",
"UserInAccountPermission_LicenseAdmin_Read",
"UserInAccountPermission_LicenseDefinitionAdmin_Modify",
"UserInAccountPermission_LicenseDefinitionAdmin_Read",
"UserInAccountPermission_LimitedCartDiscountAdmin_Modify",
"UserInAccountPermission_LimitedCartDiscountAdmin_Read",
"UserInAccountPermission_Management_Management",
"UserInAccountPermission_Nodes_CreateNodes",
"UserInAccountPermission_Nodes_DeleteNodes",
"UserInAccountPermission_Nodes_PublishNodes",
"UserInAccountPermission_Nodes_ReadNodes",
"UserInAccountPermission_Nodes_UpdateNodes",
"UserInAccountPermission_OrderAdmin_Modify",
"UserInAccountPermission_OrderAdmin_Read",
"UserInAccountPermission_PlacementContactPerson_Access",
"UserInAccountPermission_ProductAdmin_Modify",
"UserInAccountPermission_ProductAdmin_Read",
"UserInAccountPermission_ReportAdmin_Modify",
"UserInAccountPermission_ReportAdmin_Read",
"UserInAccountPermission_SettingsAdmin_Modify",
"UserInAccountPermission_SettingsAdmin_Read",
"UserInAccountPermission_Submissions_ReadSubmissions",
"UserInAccountPermission_System_Owner",
"UserInAccountPermission_TagAdmin_Modify",
"UserInAccountPermission_TagAdmin_Read",
"UserInAccountPermission_TagAdmin_Select",
"UserInAccountPermission_Tags_CreateTags",
"UserInAccountPermission_Tags_DeleteTags",
"UserInAccountPermission_Tags_ReadTags",
"UserInAccountPermission_Tags_UpdateTags",
"UserInAccountPermission_Trend_Modify",
"UserInAccountPermission_Trend_Read",
"UserInAccountPermission_VocabAdmin_ModifyWordPackages",
"UserInAccountPermission_VocabAdmin_ReadWordPackages",
'%future added value'
]